### PR TITLE
adds a function to visualize the generated graph

### PR DESCRIPTION
**Pull request by dfalbel**

### CODE REVIEW

**Comment by t-kalinowski** [comment]
Thanks for this, this is great! I think it'll be helpful for what I'm working on now. I'm in the middle of refactoring of ag_if() to use tf's concrete_functions, and unfortunately that requires rethinking loop control flow handling... I'm hoping to push that change up this weekend.

**Comment by dfalbel** [comment]
Great! I took a greater look at your code today. I'm starting to better understand it, but still not enough to  be able to contribute. 

What TF version are you targeting right now? I was testing with TF 2.0 and couldn't make it work.

**Comment by t-kalinowski** [comment]
I've only been testing on version 1.14 without eager mode enabled. I suppose I should be testing against 2.0 also, but during development I find it a little easier with eager mode off for this.

**Comment by dfalbel** [comment]
I see! I saw that some args available in 1.14 were deprecated for instance `strict` in `tf.cond`.

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/cond vs https://www.tensorflow.org/api_docs/python/tf/cond

**Comment by t-kalinowski** [comment]
I didn't know that, thanks for pointing it out. I think i should be able to manage that from the R side by always using dictionaries instead of singleton lists or tuples, to avoid the unpacking. Then we won't have to supply a `strict = FALSE` argument

**Comment by t-kalinowski** [comment]
Quick update. I just merged a pretty substantial rework of `if` and `break`/`next`. All the current tests pass, but the testing suite for conditionals needs to cover more edge cases. If you're looking for areas to contribute, one way would be to add more tests:

+  check that unmodified nested objects really are untouched (checked with `identical` before and after.
+  check that control dependencies recorded in a branch really are contained to that one branch `should be tested using stopifnot`
+  check that things everything works with deep nesting. (e.g, that `while` still has the same behavior even if it's all under one `if` branch.
+  test that undefs in nested structures work.

If you write a test that you think should pass but currently doesn't, pleas add a `skip` to it. If you add a test for a feature that you think should be added in the future, please leave the line with the actual test (the one that starts with `expect_` commented. I'm trying to keep all tests on the master branch passing at all times. 

There is a WIP version of `ag_print` that I started on, I'll try to wrap that up this week then get started tidying up the code base and documenting. No worries if you don't get to it before me.

Based on the current pace I think I'm aiming to get this on CRAN sometime within the next month, but I'm not setting myself any hard deadline.

**Comment by dfalbel** [comment]
@t-kalinowski That's great news! I'll take a look later this week.

**Pull request merged**
